### ISSUE TITLE
Use renovate for bumping the versions in the YAML

### ISSUE THREAD

**Issue by jpkrohling** [jpkrohling/otelcol-distributions#20]
@secustor wrote a blog post on how to use renovate to update the manifests: https://secustor.dev/blog/renovate_managing_a_ocb_distribution/ . It would be great to adopt this in this repository here.

**Comment by secustor** [comment]
Do you want to use the hosted App or self hosted?    

In the first case you have to install it first before anybody else can pick it up. 
https://github.com/apps/renovate

**Comment by jpkrohling** [comment]
Installed! https://github.com/jpkrohling/otelcol-distributions/pull/21

**Comment by jpkrohling** [comment]
@secustor , there's a new version of the collector available. Would you like to send a PR to configure renovate to bump them?

**Comment by secustor** [comment]
Yeah I can do that. It should be possible to provide you one later today.
